# -*- coding: utf-8 -*-
"""addition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSn-NNaytEobJbQSe3MYLNs3_TrX-BLh
"""

a,b = 10,20
print(a+b)