# -*- coding: utf-8 -*-
"""square.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HRtktxyUGA8lGhytgOPkB-b0xXcbW5_8
"""

n = 7
print(n*n)